#!/bin/bash


#method=$1
#hostname=$2

#case "$1" in
#    rm)
#    echo 'fonction rm '$2
#    exit 0;;
#    ls)
#    echo 'function list '$2
#    exit 0;;
#    mkhost)
#    mkhost($2);
#    exit 0;;
#esac



$hostname=$1;
owner=$(who am i | awk '{print $1}')
email='webmaster@localhost'

sitesEnableDir='/etc/apache2/sites-enabled'
sitesAvailableDir='/etc/apache2/sites-available/'
apacheHtmlDir='/var/www/html'
sitesAvailabledomain=$sitesAvailable$domain.conf

#make folders
mkdir -pv $hostname/$hostname

#make symbolic link
sudo ln -svfi `pwd`/$hostname/ $apacheHtmlDir/

#add hostname know hosts

#if [ cat /etc/hosts | grep -w $hostname ]
if grep -qw "$hostname" /etc/hosts
then
	echo $hostname exist deja
else
	sudo sed -i "1i127.0.0.1	$hostname" /etc/hosts
fi

#write VHost

template="
<VirtualHost *:80>
	# The ServerName directive sets the request scheme, hostname and port that
	# the server uses to identify itself. This is used when creating
	# redirection URLs. In the context of virtual hosts, the ServerName
	# specifies what hostname must appear in the request's Host: header to
	# match this virtual host. For the default virtual host (this file) this
	# value is not decisive as it is used as a last resort host regardless.
	# However, you must set it for any further virtual host explicitly.
	#ServerName www.example.com

	DocumentRoot $apacheHtmlDir/$hostname/$hostname
	ServerName $hostname

	<Directory $apacheHtmlDir/$hostname/$hostname>
		Options Indexes FollowSymLinks MultiViews
		AllowOverride All
		<RequireAny>
			Require host localhost
			Require ip 127.0.0.1
			Require ip 192.168.1
		</RequireAny>
	</Directory>

	# Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
	# error, crit, alert, emerg.
	# It is also possible to configure the loglevel for particular
	# modules, e.g.
	#LogLevel info ssl:warn

	ErrorLog 	`pwd`/$hostname/error.log
	CustomLog 	`pwd`/$hostname/access.log combined

	# For most configuration files from conf-available/, which are
	# enabled or disabled at a global level, it is possible to
	# include a line for only one particular virtual host. For example the
	# following line enables the CGI configuration for this host only
	# after it has been globally disabled with \"a2disconf\".
	#Include conf-available/serve-cgi-bin.conf
</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
"

		echo  "$template" > $hostname/$hostname.conf
		sudo ln -svfi `pwd`/$hostname/$hostname.conf $sitesAvailableDir/
		sudo ln -svfi $sitesAvailableDir/$hostname.conf $sitesEnableDir/

#restart apache
sudo service apache2 reload

